# home for all experiments except for projectile avoidance
default: [-1.0, -1.0, 0, 1.5708, -0.7854,  1.5708, -0.7854,  1.5708, 1.3100]

# unused projectile configuration
# projectile1: [-2.0, 1.0, 0, 1.5708, -0.7854,  1.5708, -0.7854,  1.5708, 1.3100]

# configuration used for projectile experiments
projectile2: [-1.5, 2.5, -1.5708, 1.5708, -0.7854,  1.5708, -0.7854,  1.5708, 1.3100]
