base_to_arm_transform:
  rpy:
  - -0.0029875896871089935
  - 0.0049049430526793
  - 0.022497495636343956
  xyz:
  - 0.0026474562473595142
  - -0.014238077215850353
  - 0.012634866870939732
ee_to_tray_transform:
  rpy:
  - 2.7763423919677734
  - -1.539000153541565
  - 0.3686171770095825
  xyz:
  - 0.035179462283849716
  - -0.0007434024009853601
  - 0.3066823184490204
