T1:
  rpy:
  - -0.0030255659949034452
  - 0.0033869966864585876
  - 0.01892634853720665
  xyz:
  - 0.0038440413773059845
  - -0.014463288709521294
  - 0.011061681434512138
T2:
  rpy:
  - 2.7803311347961426
  - -1.5421779155731201
  - 0.3738003969192505
  xyz:
  - 0.036712437868118286
  - -0.0004053786105941981
  - 0.308562308549881
