#Cfg file specifying FRANKA PANDA ARM
panda:
  arm:
    path:
      'robot/franka_panda/panda.urdf'  # TODO
    pose:
      [0, 0, 0]
    orn:
      [0, 0, 0]
    is_static:
      True
  base: 'None'

  # default perls2
  neutral_joint_angles: [0.0, -0.524, 0.0, -2.617, 0.0, 2.094, 0.0]

  # object balancing
  # neutral_joint_angles: [0, -0.7854, 0, -1.5708, 0, 2.3562, -0.7854]

  limb_joint_names: [
    'panda_link0',
    'panda_link1',
    'panda_link2',
    'panda_link3',
    'panda_link4',
    'panda_link5',
    'panda_link6',
  ]

  # TODO: Change these to actual values. with gripper.
  # Height of the limb (installed on the base) from the ground, for computing IK.
  limb_height: 0.9
  # Link name of the end effector, for computing IK.
  end_effector_name: 'right_hand'
  # Joint name of the left finger of the gripper.
  l_finger_name: 'panda_leftfinger'
  # Joint name of the right finger of the gripper.
  r_finger_name: 'panda_rightfinger'
  # Link name of the left finger tip of the gripper.
  l_finger_tip_name: 'r_gripper_l_finger_tip'
  # Link name of the right finger tip of the gripper.
  r_finger_tip_name: 'r_gripper_r_finger_tip'

  # Default maximum joint velocity ratio, chosen from (0, 1].
  # Set it to 1.0 for data collection, 0.3 for demo.
  limb_max_velocity_ratio: 0.01

  # Threshold (in rads) for each joint for position control.
  limb_position_threshold: 0.008726640

  # Threshold (in rads) for each joint for position control.
  limb_velocity_threshold: 0.75

  # Step size of a gripper trajectory.
  end_effector_step: 0.02
